# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo_test_distribute' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo_test_distribute

  target 'demo_test_distributeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo_test_distributeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
